# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Form-Maker
version:      0.03
version_from: lib/Form/Maker.pm
installdirs:  site
requires:
    Class::Data::Inheritable:      0
    Email::Valid:                  0.15
    HTML::Element:                 0
    Module::Pluggable:             0
    Test::More:                    0
    UNIVERSAL::moniker:            0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
